# .github/workflows/deploy.yml
name: Build & Deploy (GitHub Pages + Cordova)

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Build for GitHub Pages
        env:
          BUILD_TARGET: web
        run: npm run build -- --mode production

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: web
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4

  cordova:
    needs: web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0" || true
          yes | sdkmanager --licenses

      - name: Build web assets for Cordova
        run: npm run build:cordova-www

      - name: Add Android platform
        run: npx cordova platform add android

      - name: Build Cordova Android (release APK)
        run: npm run build:cordova-apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: evil-invaders-android-apk
          path: |
            cordova/platforms/android/app/build/outputs/apk/**/*.apk
